# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length               = 120
target-version            = ['py38', 'py39', 'py310', 'py311']
include                   = '\.pyi?$'
skip-string-normalization = true
# We use preview style for formatting Black itself. If you
# want stable formatting across releases, you should keep
# this off.
preview = true

[tool.isort]
profile = "black"

# [ruff configurations](https://github.com/charliermarsh/ruff#configuration)
[tool.ruff]
line-length = 120
fix         = false # don't fix by default
# # Always autofix, but never try to fix:
# # - `F401`: (unused imports)
# # - `F841`: (unused variables)
# fix       = true
# unfixable = ["F401", "F841"]
# Assume the minimum version is Python 3.8
target-version = 'py38'
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

select = [
    "F",    # Pyflakes
    "E",    # Pycodestyle
    "W",
    "N",    # pep8-naming
    "B",    # flake8-bugbear
    "I001", # isort
    "T100", # flake8-debugger
]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    ".vscode",
    ".idea",
    ".history",
]

    [tool.ruff.per-file-ignores]
    # Ignore rules:
    # - `E402`: [Module level import not at top of file](https://www.flake8rules.com/rules/E402.html)
    # - `F401`: (imported but unused)
    "__init__.py" = ["E402", "F401"]

    [tool.ruff.isort]
    known-first-party = []
    known-third-party = []

    [tool.ruff.pep8-naming]
    classmethod-decorators = ["classmethod"]
